### ISSUE TITLE
No module named FileDialog

### ISSUE THREAD

**Issue by mcingotti** [mauroalberti/qProf#11]
Hi

today I have this error message:
![cattura](https://user-images.githubusercontent.com/43775440/49933695-9ddba080-fecc-11e8-8d60-a9f77eeb27ec.JPG)
could you help me?
best regards

**Comment by mauroalberti** [comment]
Sorry for the late replay, I noticed just a few minutes ago.
Possibly you have already solved the issue.

To me, it seems more of a ?web site QGIS related issue, wrongly signalling errors in some plugins.
If you just download the plugin from the QGIS plugin repository web site and install it as a zip file, does it work?

mauro
