### ISSUE TITLE
Remove deprecated import gdal

### ISSUE THREAD

**Issue by PeterPetrik** [mauroalberti/qProf#15]
QGIS on macOS uses GDAL 3.2.1 that removed the deprecated import of GDAL, please see https://pypi.org/project/GDAL/
To support macOS 3.16 LTR and macOS 3.18, please fix the code with:

```
try:
    from osgeo import gdal
except ImportError:
    import gdal
```

detto for from ogr, osr,gdal_array and gdalconst imports

details: https://github.com/qgis/QGIS-Mac-Packager/issues/114

**Comment by mauroalberti** [comment]
Thanks, will change for next release that however has many other changes and would require 2-3 months to be released.

**Comment by mauroalberti** [comment]
Submitted to QGIS plugin repository the version 0.4.4, that should fix the problem.
