### ISSUE TITLE
Cannot profile this gpx

### ISSUE THREAD

**Issue by luca76** [mauroalberti/qProf#5]
Test this gpx.

[prova.gpx.zip](https://github.com/mauroalberti/qProf/files/1065944/prova.gpx.zip)

**Comment by mauroalberti** [comment]
I confirm the problem in visualizing this file. Will investigate the reason(s) next days.

**Comment by mauroalberti** [comment]
In the new branch "gsf_integration" this problem is solved.
However I am doing a heavy refactoring also in geological data processing and plotting, so I do not plan to release it before a few months.

**Comment by mauroalberti** [comment]
With the release of 0.3.4 in GitHub this issue should be solved.

**Comment by lucamanga** [comment]
Perfect! Now It's working :-) You can close this bug!

**Comment by mauroalberti** [comment]
Closed!
