### ISSUE TITLE
No module named urllib.request

### ISSUE THREAD

**Issue by L-I-S-T-A** [mauroalberti/qProf#6]
I cannot install qProf plugin, I receive the message: "ImportError: No module named urllib.request".
In the directory "Python36" there are the directories and file  "Python36\Lib\urllib\request.py"!
Where could be the problem?

**Comment by mauroalberti** [comment]
But from your message I understand that you are using Python 3.6. 
qProf is currently just for QGIS 2.x, that uses Python 2.7 or however 2.x. Even if you have both Python 3 .x and 2.x, and your QGIS is using (as expected) Python 2.x, _urlib_ is a standard library module, so it should be already available in your Python 2.x.

Which OS and QGIS version are you using? And how did you try to install qProf? From the QGIS Python plugin manager or in any other way?

**Comment by L-I-S-T-A** [comment]
I'm using Windows 10 and QGIS 2.18.14 and QGIS 2.14.20. I installed qProf
from Python plugin manager.
In Python 2.x I don't find *urllib*. I find only *urllib3* directory in the
path: ...\Lib\site-packages\ and the file *request.py* in this directory.

Giulio F. Pappafico

http://listauniurb.jimdo.com/
Skype: pappafico2

2017-11-19 19:09 GMT+01:00 alberese <notifications@github.com>:

**Comment by mauroalberti** [comment]
In qProf the only use of an internet-related module should be for opening the help html file. But the used module is webbrowser, not urllib. And also webbrowser is a standard library Python module, so it should be there. 
Would it be possible to look at the full stack of error-messages, that ends with "ImportError: No module named urllib.request", to understand where and why urllib is called?
Moreover, when typing in the QGIS Python console:
_import webbrowser_
_webbrowser.open("http://www.google.com")_
what are the results?

**Comment by L-I-S-T-A** [comment]
Sorry for the delay of my answer,
I completely reinstalled QGIS and the various requested packages and now
qProf runs regularly.

Thank you very much for your help and for the suggestions.

Giulio



2017-11-20 22:33 GMT+01:00 alberese <notifications@github.com>:

**Comment by mauroalberti** [comment]
Good that you solved the problem...

mauro
