### ISSUE TITLE
Tkinter module missing

### ISSUE THREAD

**Issue by enviroscop** [mauroalberti/qProf#9]
Hello,
since the last update of Qgis 2.18, I can no longer use qprof. Qgis does not find "Tkinter". I think it's because it's been renamed tkinter without de capital letter. Is there an easy way to fix the problem? Thanks

![qprof2](https://user-images.githubusercontent.com/36412048/36101421-97e1a204-1009-11e8-9bfe-7896dff170df.PNG)

**Comment by mauroalberti** [comment]
Unfortunately I know of no easy way to bypass this problem in Windows. 
Possibly using the osgeo4win installation modality instead of the standalone installer it could not present itself, since I believe it is related to a problematic Python customization inside the standalone QGIS installation.
